using Marten.Schema;
using Marten;
using Conduit.API.Dso;

namespace Conduit.API.Seed;

public class InitialData : IInitialData
{
    private readonly object[] _initialData;

    public InitialData(params object[] initialData)
    {
        _initialData = initialData;
    }

    public async Task Populate(IDocumentStore store, CancellationToken cancellation)
    {
        await using var session = store.LightweightSession();
        // Marten UPSERT will cater for existing records
        session.Store(_initialData);
        await session.SaveChangesAsync();
    }
}

public static class InitialDatasets
{
    public static readonly ProfileDso[] Profiles =
    {
        new ProfileDso{ Id = "2", Username = "Bob", Bio = "The World's Greatest Secret Agent", Image = "https://static.productionready.io/images/smiley-cyrus.jpg", Following = false },
        new ProfileDso{ Id = "1", Username = "Alice", Bio = "The Fastest Mouse in all of Mexico", Image = "https://static.productionready.io/images/smiley-cyrus.jpg", Following = false }
    };

    public static readonly ArticleDso[] Articles =
    {
        new ArticleDso{ Slug = "how-to-train-your-dragon", Title = "How to train your dragon", Description = "Ever wonder how?", Body = "You have to believe", CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "dragons", "training" }, FavoritedBy = new HashSet<string>(),  Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-quick-brown-fox", Title = "The quick brown fox", Description = "Jumped over the lazy dog", Body = "The quick brown fox jumped over the lazy dog", CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "quick", "brown", "fox" }, FavoritedBy = new HashSet<string>(), Author = Profiles[1], Comments = Comments },
        new ArticleDso{ Slug = "exploring-the-galaxy", Title = "Exploring the Galaxy", Description = "A journey beyond the stars", Body = "Space, the final frontier...", CreatedAt = DateTime.UtcNow.AddDays(-10), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "space", "galaxy", "exploration" }, FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "coding-in-csharp", Title = "Coding in C#", Description = "Getting started with C#", Body = "C# is a modern, object-oriented programming language intended to create simple yet robust programs.", CreatedAt = DateTime.UtcNow.AddDays(-20), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "programming", "csharp", "dotnet" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "baking-bread-at-home", Title = "Baking Bread at Home", Description = "The joy of baking your own bread", Body = "There's nothing like the smell of fresh bread in the morning.", CreatedAt = DateTime.UtcNow.AddDays(-30), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "baking", "bread", "home" }, FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-meditation", Title = "The Art of Meditation", Description = "Finding peace in a busy world", Body = "Meditation can help you find a sense of calm and inner peace.", CreatedAt = DateTime.UtcNow.AddDays(-40), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "meditation", "mindfulness", "peace" }, FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-reading", Title = "The Joy of Reading", Description = "Discovering new worlds through books", Body = "Reading can take you to places you've never been before.", CreatedAt = DateTime.UtcNow.AddDays(-50), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "reading", "books", "literature" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-cooking", Title = "The Art of Cooking", Description = "Creating delicious meals at home", Body = "Cooking is an art form that can bring people together.", CreatedAt = DateTime.UtcNow.AddDays(-60), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "cooking", "food", "recipes" }, FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-writing", Title = "The Joy of Writing", Description = "Expressing yourself through words", Body = "Writing can be a powerful form of self-expression.", CreatedAt = DateTime.UtcNow.AddDays(-70), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "writing", "creativity", "expression" },  FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-drawing", Title = "The Art of Drawing", Description = "Bringing your imagination to life", Body = "Drawing is a creative outlet that allows you to express yourself visually.", CreatedAt = DateTime.UtcNow.AddDays(-80), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "drawing", "art", "creativity" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-painting", Title = "The Joy of Painting", Description = "Creating beautiful works of art", Body = "Painting is a relaxing and rewarding hobby that can bring out your inner artist.", CreatedAt = DateTime.UtcNow.AddDays(-90), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "painting", "art", "creativity" }, FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-photography", Title = "The Art of Photography", Description = "Capturing moments in time", Body = "Photography is a way to freeze a moment in time and preserve it forever.", CreatedAt = DateTime.UtcNow.AddDays(-100), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "photography", "art", "creativity" },  FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-travel", Title = "The Joy of Travel", Description = "Exploring new places and cultures", Body = "Traveling can open your eyes to new experiences and broaden your horizons.", CreatedAt = DateTime.UtcNow.AddDays(-110), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "travel", "adventure", "culture" },  FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-dance", Title = "The Art of Dance", Description = "Expressing yourself through movement", Body = "Dance is a universal language that can convey emotions and tell stories without words.", CreatedAt = DateTime.UtcNow.AddDays(-120), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "dance", "art", "creativity" },  FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-music", Title = "The Joy of Music", Description = "Listening to your favorite tunes", Body = "Music has the power to uplift your spirits and soothe your soul.", CreatedAt = DateTime.UtcNow.AddDays(-130), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "music", "art", "creativity" },  FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-theater", Title = "The Art of Theater", Description = "Bringing stories to life on stage", Body = "Theater is a collaborative art form that can transport audiences to different worlds and times.", CreatedAt = DateTime.UtcNow.AddDays(-140), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "theater", "art", "creativity" },  FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-film", Title = "The Joy of Film", Description = "Watching your favorite movies", Body = "Film is a powerful medium that can entertain, educate, and inspire audiences.", CreatedAt = DateTime.UtcNow.AddDays(-150), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "film", "movies", "cinema" },  FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-design", Title = "The Art of Design", Description = "Creating beautiful and functional objects", Body = "Design is all around us, from the clothes we wear to the buildings we live in.", CreatedAt = DateTime.UtcNow.AddDays(-160), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "design", "art", "creativity" }, FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-gardening", Title = "The Joy of Gardening", Description = "Growing your own fruits and vegetables", Body = "Gardening is a rewarding hobby that can provide fresh, healthy produce for you and your family.", CreatedAt = DateTime.UtcNow.AddDays(-170), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "gardening", "plants", "vegetables" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-fishing", Title = "The Art of Fishing", Description = "Casting a line and reeling in the big one", Body = "Fishing is a relaxing and enjoyable pastime that can bring you closer to nature.", CreatedAt = DateTime.UtcNow.AddDays(-180), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "fishing", "outdoors", "nature" },  FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-camping", Title = "The Joy of Camping", Description = "Sleeping under the stars and roasting marshmallows", Body = "Camping is a fun and affordable way to enjoy the great outdoors with family and friends.", CreatedAt = DateTime.UtcNow.AddDays(-190), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "camping", "outdoors", "nature" },  FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-hiking", Title = "The Art of Hiking", Description = "Exploring the great outdoors on foot", Body = "Hiking is a great way to stay active and enjoy the beauty of nature.", CreatedAt = DateTime.UtcNow.AddDays(-200), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "hiking", "outdoors", "nature" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-cycling", Title = "The Joy of Cycling", Description = "Riding your bike through the countryside", Body = "Cycling is a fun and eco-friendly way to explore your local area and stay fit.", CreatedAt = DateTime.UtcNow.AddDays(-210), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "cycling", "outdoors", "exercise" },  FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-yoga", Title = "The Art of Yoga", Description = "Finding balance and inner peace", Body = "Yoga is a mind-body practice that can help you relax, de-stress, and improve your overall well-being.", CreatedAt = DateTime.UtcNow.AddDays(-220), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "yoga", "mindfulness", "wellness" },  FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-meditation", Title = "The Joy of Meditation", Description = "Finding peace and tranquility within", Body = "Meditation is a practice that can help you find inner peace, reduce stress, and improve your mental well-being.", CreatedAt = DateTime.UtcNow.AddDays(-230), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "meditation", "mindfulness", "wellness" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-mindfulness", Title = "The Art of Mindfulness", Description = "Living in the present moment", Body = "Mindfulness is a practice that can help you stay focused, calm, and present in your daily life.", CreatedAt = DateTime.UtcNow.AddDays(-240), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "mindfulness", "meditation", "wellness" },  FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-wellness", Title = "The Joy of Wellness", Description = "Taking care of your mind, body, and spirit", Body = "Wellness is a holistic approach to health and happiness that encompasses physical, mental, and emotional well-being.", CreatedAt = DateTime.UtcNow.AddDays(-250), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "wellness", "health", "happiness" },  FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-happiness", Title = "The Art of Happiness", Description = "Finding joy and contentment in life", Body = "Happiness is a state of mind that can be cultivated through positive thinking, gratitude, and self-care.", CreatedAt = DateTime.UtcNow.AddDays(-260), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "happiness", "joy", "contentment" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-peace", Title = "The Joy of Peace", Description = "Finding inner peace and serenity", Body = "Peace is a state of mind that can be achieved through mindfulness, meditation, and self-reflection.", CreatedAt = DateTime.UtcNow.AddDays(-270), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "peace", "serenity", "tranquility" }, FavoritedBy = new HashSet<string>{"1", "2"}, Author = Profiles[0], Comments = [] },
        new ArticleDso{ Slug = "the-art-of-love", Title = "The Art of Love", Description = "Expressing love and affection for others", Body = "Love is a powerful force that can bring people together, heal wounds, and create lasting bonds.", CreatedAt = DateTime.UtcNow.AddDays(-280), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "love", "affection", "relationships" }, FavoritedBy = new HashSet<string>{"1"}, Author = Profiles[1], Comments = [] },
        new ArticleDso{ Slug = "the-joy-of-friendship", Title = "The Joy of Friendship", Description = "Building strong and lasting relationships", Body = "Friendship is a special bond that can bring joy, support, and companionship to your life.", CreatedAt = DateTime.UtcNow.AddDays(-290), UpdatedAt = DateTime.UtcNow, TagList = new List<string>{ "friendship", "relationships", "companionship" }, FavoritedBy = new HashSet<string>{"2"}, Author = Profiles[0], Comments = [] }

    };

    public static readonly List<CommentDso> Comments =
    [
        new CommentDso("1", "Great article!", DateTime.UtcNow, DateTime.UtcNow, Profiles[0]),
        new CommentDso("2", "Great article!", DateTime.UtcNow, DateTime.UtcNow, Profiles[1])
    ];
}
